### ISSUE TITLE
everything done right, still not injecting?

### ISSUE THREAD

**Issue by fiveseven57memer** [ThaisenPM/Cheat-Loader-CSGO-2.0#4]
i did everything right, it says "Successfully Injected" and closes itself, but it's still not injected in a game?

**Comment by ThaisenPM** [comment]
Check your DLL, make sure the hmodule DOES NOT = 0x000000

**Comment by machado-rev** [comment]
Hi @ThaisenPM how are you?


I know that is related with this line:

`label1.Text = $"hmodule = 0x{injector.Inject(file).ToInt64():x8}";`

When I inject the loader give me a message that is succesfully injected BUT crash CS GO.

I know that is related with hmodule, but my dll are protected (for self preservation purpose)!

So, what can I do?

Thank you

**Comment by ThaisenPM** [comment]
@machado-rev Game crashes are related to your DLL. Make sure your offsets and scructs are up to date

**Comment by machado-rev** [comment]
Hi, thank you for your reply!

Interesting that my DLL I can inject with my own injector (and I still want to use your injector that is in the code).

Ive tried some new codes but is impossible.


My dll are protected with VMPROTECT? Do you think that is possible that the problem is related with VMPROTECT?
